image: Visual Studio 2017
version: 1.0.{build}
build_script:
- ps: ./src/cloud/functions/package.ps1
- ps: Push-AppveyorArtifact packaged-content/nether-serverless.zip -FileName nether-serverless.Zip -Type WebDeployPackage
